### PR TITLE
Modified tree links position and prevent overlapping with sensors links

### PR DESCRIPTION
**Pull request by ehab74**
The tree links shouldn't overlap now with the sensors links.

Also, the scroll bar of the sidnav should stick to the sensors menu height and on zooming in, there will be a scroll bar for the whole sidenav to show the tree links in addition scrolling inside the sensors menu,

### CODE REVIEW

**Comment by ChristophPopp** [comment]
The links to the other trees should always be visible in the bottom part of the sidenav. Scrolling should not have an effect on the visibility of the links. In the following screenshot, the scrollbar is actually not needed at all, because there is much blank space anyway.
image

**Comment by ehab74** [comment]
It should be fixed now.

**Comment by ChristophPopp** [comment]
Now the bottom part of the scrollbar seems to be hidden behind the links to the other trees.
image

Could we change the design that the scrollable area (and thus also the scrollbar) starts under the search field and ends above the other tree links?
A horizontal separator line above the tree links might also be a good idea to avoid confusion and disorientation in the sidenav area.

**Comment by ChristophPopp** [comment]
Looks much better now!
Could you please still add a horizontal separator line above the tree links?
And another thought that just came to my mind: I think it would be more intuitive if the little arrow symbols that indicate that the decomposition blocks in the sidenav can be expanded would turn upside down when they currently are expanded. Then, the arrow points upwards and indicates that the decomposition block collapses again when you click on it.

**Comment by ehab74** [comment]
> Looks much better now! Could you please still add a horizontal separator line above the tree links? 
Done

> And another thought that just came to my mind: I think it would be more intuitive if the little arrow symbols that indicate that the decomposition blocks in the sidenav can be expanded would turn upside down when they currently are expanded. 

That's a good idea. I added it.

**Review by ChristophPopp — APPROVED** [review]

**Pull request merged**
