### PR TITLE
36 clicking on search result does not open the node

### PR DESCRIPTION
**Pull request by ehab74**
It should be working. 

About the animation of the node if it wasn't already displayed, do you feel it is not important or doesn't add much?

### CODE REVIEW

**Comment by ChristophPopp** [comment]
> About the animation of the node if it wasn't already displayed, do you feel it is not important or doesn't add much?

I think the animation is still good in this case, since the user can see that the part of the tree changes that was visible before.
However, it would be useful to also change the viewbox (smoothly) such that the searched and highlighted node is visible in the viewbox.

**Comment by ehab74** [comment]
Okay i made the viewbox to move to the node found by the search. 

One last thing, if the node found by the search bar is already displayed, do you want the viewbox to move to it or it is not important?

**Comment by ChristophPopp** [comment]
> Okay i made the viewbox to move to the node found by the search.
> 
> One last thing, if the node found by the search bar is already displayed, do you want the viewbox to move to it or it is not important?

Nice!
If the node found in the search bar is already expanded but not within the viewbox, the viewbox should also move such that the node is visible in the viewbox for the user.

**Comment by ehab74** [comment]
> Nice! If the node found in the search bar is already expanded but not within the viewbox, the viewbox should also move such that the node is visible in the viewbox for the user.


Okay i will add it.

**Comment by ehab74** [comment]
It should be working now.

**Pull request merged**
